version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: db_username
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: sm_database_name
    ports:
      - 5432:5432

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
